server:
  port: 8080
spring:
  application:
    name: desafio-votos
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
  datasource:
    url: ${BANCO_URL:jdbc:mysql://localhost:3306/desafio_votos_db?allowPublicKeyRetrieval=true&sslMode=DISABLED}
    username: ${BANCO_USER:root}
    password: ${MYSQL_ROOT_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver

analise:
  voto:
    url: https://user-info.herokuapp.com/users

